LongName: Southern Illinois University Edwardsville
Description: Southern Illinois University Edwardsville OpenStack Cluster

ID:
AddressLine1: SIUE State Route 157
City: Edwardsville

Country: USA
State: Illinois
Zipcode: "62026"

Latitude: 38.7931
Longitude: -89.9961
